# Generated by Django 4.1.7 on 2023-04-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contatos',
            fields=[
                ('id_contato', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
