# Generated by Django 4.1.7 on 2023-04-06 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graosdaterra', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contatos',
            new_name='contato',
        ),
    ]
