# Generated by Django 4.1.7 on 2023-04-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graosdaterra', '0002_rename_contatos_contato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='numero',
            new_name='telefone',
        ),
    ]
